/* Generated By:JavaCC: Do not edit this line. DavinDBMSParserConstants.java */
//import
package davinDBMS;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface DavinDBMSParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int EXIT = 5;
  /** RegularExpression Id. */
  int INT = 6;
  /** RegularExpression Id. */
  int CHAR = 7;
  /** RegularExpression Id. */
  int DATE = 8;
  /** RegularExpression Id. */
  int CREATE_TABLE = 9;
  /** RegularExpression Id. */
  int NOT_NULL = 10;
  /** RegularExpression Id. */
  int PRIMARY_KEY = 11;
  /** RegularExpression Id. */
  int FOREIGN_KEY = 12;
  /** RegularExpression Id. */
  int REFERENCES = 13;
  /** RegularExpression Id. */
  int DROP_TABLE = 14;
  /** RegularExpression Id. */
  int DESC = 15;
  /** RegularExpression Id. */
  int INSERT_INTO = 16;
  /** RegularExpression Id. */
  int VALUES = 17;
  /** RegularExpression Id. */
  int NULL = 18;
  /** RegularExpression Id. */
  int DELETE_FROM = 19;
  /** RegularExpression Id. */
  int WHERE = 20;
  /** RegularExpression Id. */
  int OR = 21;
  /** RegularExpression Id. */
  int AND = 22;
  /** RegularExpression Id. */
  int NOT = 23;
  /** RegularExpression Id. */
  int SELECT = 24;
  /** RegularExpression Id. */
  int AS = 25;
  /** RegularExpression Id. */
  int FROM = 26;
  /** RegularExpression Id. */
  int IS_NULL = 27;
  /** RegularExpression Id. */
  int IS_NOT_NULL = 28;
  /** RegularExpression Id. */
  int SHOW_TABLES = 29;
  /** RegularExpression Id. */
  int SEMICOLON = 30;
  /** RegularExpression Id. */
  int END_OF_QUERIES = 31;
  /** RegularExpression Id. */
  int LEFT_PAREN = 32;
  /** RegularExpression Id. */
  int RIGHT_PAREN = 33;
  /** RegularExpression Id. */
  int COMMA = 34;
  /** RegularExpression Id. */
  int UNDERSCORE = 35;
  /** RegularExpression Id. */
  int INT_VALUE = 36;
  /** RegularExpression Id. */
  int SIGN = 37;
  /** RegularExpression Id. */
  int DIGIT = 38;
  /** RegularExpression Id. */
  int PERIOD = 39;
  /** RegularExpression Id. */
  int ASTERISK = 40;
  /** RegularExpression Id. */
  int COMP_OP = 41;
  /** RegularExpression Id. */
  int LEGAL_IDENTIFIER = 42;
  /** RegularExpression Id. */
  int ALPHABET = 43;
  /** RegularExpression Id. */
  int CHAR_STRING = 44;
  /** RegularExpression Id. */
  int NON_QUOTE_CHARACTERS = 45;
  /** RegularExpression Id. */
  int NON_QUOTE_SPECIAL_CHARACTERS = 46;
  /** RegularExpression Id. */
  int OPEN_QUOTE = 47;
  /** RegularExpression Id. */
  int DATE_VALUE = 48;
  /** RegularExpression Id. */
  int NNNN = 49;
  /** RegularExpression Id. */
  int NN = 50;
  /** RegularExpression Id. */
  int SPACE = 51;
  /** RegularExpression Id. */
  int CLOSE_QUOTE = 52;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int STRING = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"exit\"",
    "\"int\"",
    "\"char\"",
    "\"date\"",
    "<CREATE_TABLE>",
    "\"not null\"",
    "\"primary key\"",
    "\"foreign key\"",
    "\"references\"",
    "<DROP_TABLE>",
    "\"desc\"",
    "<INSERT_INTO>",
    "\"values\"",
    "\"null\"",
    "<DELETE_FROM>",
    "\"where\"",
    "<OR>",
    "<AND>",
    "\"not\"",
    "\"select\"",
    "\"as\"",
    "\"from\"",
    "\"is null\"",
    "\"is not null\"",
    "\"show tables\"",
    "\";\"",
    "<END_OF_QUERIES>",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\"_\"",
    "<INT_VALUE>",
    "<SIGN>",
    "<DIGIT>",
    "\".\"",
    "\"*\"",
    "<COMP_OP>",
    "<LEGAL_IDENTIFIER>",
    "<ALPHABET>",
    "<CHAR_STRING>",
    "<NON_QUOTE_CHARACTERS>",
    "<NON_QUOTE_SPECIAL_CHARACTERS>",
    "\"\\\'\"",
    "<DATE_VALUE>",
    "<NNNN>",
    "<NN>",
    "\" \"",
    "\"\\\'\"",
  };

}
